In [4]:
import pandas as pd
import numpy as np

In [3]:
df1 = pd.read_csv('Covid.csv')
df1.head()

,state,confirmed,active,passive,deaths,dose1,dose2,dose3,precaution_dose,total_doses,population
0,Andaman and Nicobar,10742,1.0,10612,129.0,313284.0,320383,236936.0,53427.0,991263,426251.0
1,Andhra Pradesh,2339067,3.0,2324331,14733.0,40643161.0,43549055,11703273.0,6579565.0,110556756,52883163.0
2,Arunachal Pradesh,66890,NaN,66594,296.0,860442.0,747177,NaN,58618.0,1911760,1528296.0
3,Assam,746100,0.0,738065,8035.0,22549957.0,20561790,2082670.0,1259853.0,50284713,34586234.0
4,Bihar,851379,15.0,839062,12302.0,62944633.0,59144387,11983504.0,3868082.0,157197041,119461013.0

In [5]:
df2 = pd.read_csv('Covid.csv', na_values = 'Goa')
df2

,state,confirmed,active,passive,deaths,dose1,dose2,dose3,precaution_dose,total_doses,population
0,Andaman and Nicobar,10742,1.0,10612,129.0,313284.0,320383,236936.0,53427.0,991263,426251.0
1,Andhra Pradesh,2339067,3.0,2324331,14733.0,40643161.0,43549055,11703273.0,6579565.0,110556756,52883163.0
2,Arunachal Pradesh,66890,NaN,66594,296.0,860442.0,747177,NaN,58618.0,1911760,1528296.0
3,Assam,746100,0.0,738065,8035.0,22549957.0,20561790,2082670.0,1259853.0,50284713,34586234.0
4,Bihar,851379,15.0,839062,12302.0,62944633.0,59144387,11983504.0,3868082.0,157197041,119461013.0
5,Chandigarh,99348,6.0,98161,NaN,1089254.0,917701,48480.0,63046.0,2282281,1182104.0
6,Chhattisgarh,1177749,6.0,1163597,14146.0,NaN,18534989,5737679.0,1804891.0,49148991,28566990.0
7,Dadra and Nagar Haveli and Daman and Diu,11591,0.0,11587,4.0,730746.0,594929,136967.0,NaN,1578492,657391.0
8,Delhi,2007188,35.0,1980632,26521.0,NaN,14348835,2312803.0,1053393.0,37366540,18802494.0
9,NaN,259079,26.0,255040,4013.0,1354828.0,1224173,60838.0,76559.0,2872582,1542750.0
10,Gujarat,1277557,41.0,1266473,11043.0,49314588.0,49428283,13459618.0,5938121.0,127793995,63907200.0
11,Haryana,1056602,43.0,1045845,10714.0,21955717.0,18732346,NaN,701811.0,45457359,27388008.0
12,Himachal Pradesh,312644,23.0,308408,4213.0,6041658.0,5780254,1485328.0,823689.0,15278680,7316708.0
13,Jammu and Kashmir,479410,17.0,474608,4785.0,9941757.0,10386967,930096.0,669871.0,24738045,14046258.0
14,Jharkhand,442570,NaN,437236,5331.0,21300448.0,16046070,1306687.0,664308.0,43689818,NaN
15,Karnataka,4071893,1275.0,4030311,40307.0,50016690.0,50455767,5727031.0,4726542.0,120928298,66165886.0
16,Kerala,6828245,1389.0,6755304,71552.0,27013745.0,23791879,854595.0,2215656.0,57477992,35330888.0
17,Ladakh,29412,3.0,29178,231.0,219564.0,186942,68766.0,53990.0,564943,307204.0
18,Lakshadweep,11415,0.0,11363,52.0,56908.0,55992,15757.0,6949.0,145008,72210.0
19,Madhya Pradesh,1054918,4.0,1044138,10776.0,54140166.0,54035268,9854998.0,3787239.0,133590886,82342793.0
20,Maharashtra,8136588,164.0,7988008,148416.0,84644083.0,71593498,5022623.0,4450343.0,177678317,120837347.0
21,Manipur,139922,0.0,137773,2149.0,1463998.0,1225599,114004.0,165096.0,3265933,3008546.0
22,Meghalaya,96783,1.0,95158,1624.0,1332102.0,1024902,30706.0,56987.0,2621058,3276323.0
23,Mizoram,238964,0.0,238238,726.0,785749.0,668814,79573.0,67619.0,1790818,1205974.0
24,Nagaland,35986,0.0,35204,782.0,837775.0,684306,26060.0,43640.0,1737554,2189297.0
25,Odisha,1336552,91.0,1327256,9205.0,31453659.0,29949756,9995330.0,3199384.0,81445474,45429399.0
26,Puducherry,175508,5.0,173528,1975.0,912901.0,801853,303475.0,106956.0,2272617,1397707.0
27,Punjab,784205,49.0,764867,19289.0,22352681.0,19602907,799986.0,1041039.0,46970300,29611935.0
28,Rajasthan,1315455,88.0,1305714,9653.0,51103054.0,46510275,4387205.0,2995864.0,115325059,78230816.0
29,Sikkim,44319,1.0,43819,499.0,539927.0,509134,158276.0,55637.0,1360444,671720.0
30,Tamil Nadu,3594388,60.0,3556279,38049.0,56659544.0,53499923,6033504.0,3021694.0,127442647,76481545.0
31,Telengana,841324,71.0,837142,4111.0,29607672.0,29053708,10525975.0,2702159.0,77201709,38472769.0
32,Tripura,108034,0.0,107094,940.0,2658852.0,2328613,271434.0,204733.0,5916312,4057847.0
33,Uttar Pradesh,2128103,46.0,2104424,23633.0,154058287.0,147716010,35623544.0,9240735.0,390639497,228959599.0
34,Uttarakhand,449379,28.0,441600,7751.0,8180312.0,7940592,1346150.0,867047.0,20051714,11090425.0
35,West Bengal,2118606,58.0,2097016,21532.0,67300236.0,61593452,10257324.0,5491943.0,155962840,97694960.0

In [8]:
df4 = pd.read_csv('Covid.csv', na_values = ['Tripura', 0.0])
df4

,state,confirmed,active,passive,deaths,dose1,dose2,dose3,precaution_dose,total_doses,population
0,Andaman and Nicobar,10742,1.0,10612,129.0,313284.0,320383,236936.0,53427.0,991263,426251.0
1,Andhra Pradesh,2339067,3.0,2324331,14733.0,40643161.0,43549055,11703273.0,6579565.0,110556756,52883163.0
2,Arunachal Pradesh,66890,NaN,66594,296.0,860442.0,747177,NaN,58618.0,1911760,1528296.0
3,Assam,746100,NaN,738065,8035.0,22549957.0,20561790,2082670.0,1259853.0,50284713,34586234.0
4,Bihar,851379,15.0,839062,12302.0,62944633.0,59144387,11983504.0,3868082.0,157197041,119461013.0
5,Chandigarh,99348,6.0,98161,NaN,1089254.0,917701,48480.0,63046.0,2282281,1182104.0
6,Chhattisgarh,1177749,6.0,1163597,14146.0,NaN,18534989,5737679.0,1804891.0,49148991,28566990.0
7,Dadra and Nagar Haveli and Daman and Diu,11591,NaN,11587,4.0,730746.0,594929,136967.0,NaN,1578492,657391.0
8,Delhi,2007188,35.0,1980632,26521.0,NaN,14348835,2312803.0,1053393.0,37366540,18802494.0
9,Goa,259079,26.0,255040,4013.0,1354828.0,1224173,60838.0,76559.0,2872582,1542750.0
10,Gujarat,1277557,41.0,1266473,11043.0,49314588.0,49428283,13459618.0,5938121.0,127793995,63907200.0
11,Haryana,1056602,43.0,1045845,10714.0,21955717.0,18732346,NaN,701811.0,45457359,27388008.0
12,Himachal Pradesh,312644,23.0,308408,4213.0,6041658.0,5780254,1485328.0,823689.0,15278680,7316708.0
13,Jammu and Kashmir,479410,17.0,474608,4785.0,9941757.0,10386967,930096.0,669871.0,24738045,14046258.0
14,Jharkhand,442570,NaN,437236,5331.0,21300448.0,16046070,1306687.0,664308.0,43689818,NaN
15,Karnataka,4071893,1275.0,4030311,40307.0,50016690.0,50455767,5727031.0,4726542.0,120928298,66165886.0
16,Kerala,6828245,1389.0,6755304,71552.0,27013745.0,23791879,854595.0,2215656.0,57477992,35330888.0
17,Ladakh,29412,3.0,29178,231.0,219564.0,186942,68766.0,53990.0,564943,307204.0
18,Lakshadweep,11415,NaN,11363,52.0,56908.0,55992,15757.0,6949.0,145008,72210.0
19,Madhya Pradesh,1054918,4.0,1044138,10776.0,54140166.0,54035268,9854998.0,3787239.0,133590886,82342793.0
20,Maharashtra,8136588,164.0,7988008,148416.0,84644083.0,71593498,5022623.0,4450343.0,177678317,120837347.0
21,Manipur,139922,NaN,137773,2149.0,1463998.0,1225599,114004.0,165096.0,3265933,3008546.0
22,Meghalaya,96783,1.0,95158,1624.0,1332102.0,1024902,30706.0,56987.0,2621058,3276323.0
23,Mizoram,238964,NaN,238238,726.0,785749.0,668814,79573.0,67619.0,1790818,1205974.0
24,Nagaland,35986,NaN,35204,782.0,837775.0,684306,26060.0,43640.0,1737554,2189297.0
25,Odisha,1336552,91.0,1327256,9205.0,31453659.0,29949756,9995330.0,3199384.0,81445474,45429399.0
26,Puducherry,175508,5.0,173528,1975.0,912901.0,801853,303475.0,106956.0,2272617,1397707.0
27,Punjab,784205,49.0,764867,19289.0,22352681.0,19602907,799986.0,1041039.0,46970300,29611935.0
28,Rajasthan,1315455,88.0,1305714,9653.0,51103054.0,46510275,4387205.0,2995864.0,115325059,78230816.0
29,Sikkim,44319,1.0,43819,499.0,539927.0,509134,158276.0,55637.0,1360444,671720.0
30,Tamil Nadu,3594388,60.0,3556279,38049.0,56659544.0,53499923,6033504.0,3021694.0,127442647,76481545.0
31,Telengana,841324,71.0,837142,4111.0,29607672.0,29053708,10525975.0,2702159.0,77201709,38472769.0
32,NaN,108034,NaN,107094,940.0,2658852.0,2328613,271434.0,204733.0,5916312,4057847.0
33,Uttar Pradesh,2128103,46.0,2104424,23633.0,154058287.0,147716010,35623544.0,9240735.0,390639497,228959599.0
34,Uttarakhand,449379,28.0,441600,7751.0,8180312.0,7940592,1346150.0,867047.0,20051714,11090425.0
35,West Bengal,2118606,58.0,2097016,21532.0,67300236.0,61593452,10257324.0,5491943.0,155962840,97694960.0

In [10]:
df2.fillna(method = 'bfill')

,state,confirmed,active,passive,deaths,dose1,dose2,dose3,precaution_dose,total_doses,population
0,Andaman and Nicobar,10742,1.0,10612,129.0,313284.0,320383,236936.0,53427.0,991263,426251.0
1,Andhra Pradesh,2339067,3.0,2324331,14733.0,40643161.0,43549055,11703273.0,6579565.0,110556756,52883163.0
2,Arunachal Pradesh,66890,0.0,66594,296.0,860442.0,747177,2082670.0,58618.0,1911760,1528296.0
3,Assam,746100,0.0,738065,8035.0,22549957.0,20561790,2082670.0,1259853.0,50284713,34586234.0
4,Bihar,851379,15.0,839062,12302.0,62944633.0,59144387,11983504.0,3868082.0,157197041,119461013.0
5,Chandigarh,99348,6.0,98161,14146.0,1089254.0,917701,48480.0,63046.0,2282281,1182104.0
6,Chhattisgarh,1177749,6.0,1163597,14146.0,730746.0,18534989,5737679.0,1804891.0,49148991,28566990.0
7,Dadra and Nagar Haveli and Daman and Diu,11591,0.0,11587,4.0,730746.0,594929,136967.0,1053393.0,1578492,657391.0
8,Delhi,2007188,35.0,1980632,26521.0,1354828.0,14348835,2312803.0,1053393.0,37366540,18802494.0
9,Gujarat,259079,26.0,255040,4013.0,1354828.0,1224173,60838.0,76559.0,2872582,1542750.0
10,Gujarat,1277557,41.0,1266473,11043.0,49314588.0,49428283,13459618.0,5938121.0,127793995,63907200.0
11,Haryana,1056602,43.0,1045845,10714.0,21955717.0,18732346,1485328.0,701811.0,45457359,27388008.0
12,Himachal Pradesh,312644,23.0,308408,4213.0,6041658.0,5780254,1485328.0,823689.0,15278680,7316708.0
13,Jammu and Kashmir,479410,17.0,474608,4785.0,9941757.0,10386967,930096.0,669871.0,24738045,14046258.0
14,Jharkhand,442570,1275.0,437236,5331.0,21300448.0,16046070,1306687.0,664308.0,43689818,66165886.0
15,Karnataka,4071893,1275.0,4030311,40307.0,50016690.0,50455767,5727031.0,4726542.0,120928298,66165886.0
16,Kerala,6828245,1389.0,6755304,71552.0,27013745.0,23791879,854595.0,2215656.0,57477992,35330888.0
17,Ladakh,29412,3.0,29178,231.0,219564.0,186942,68766.0,53990.0,564943,307204.0
18,Lakshadweep,11415,0.0,11363,52.0,56908.0,55992,15757.0,6949.0,145008,72210.0
19,Madhya Pradesh,1054918,4.0,1044138,10776.0,54140166.0,54035268,9854998.0,3787239.0,133590886,82342793.0
20,Maharashtra,8136588,164.0,7988008,148416.0,84644083.0,71593498,5022623.0,4450343.0,177678317,120837347.0
21,Manipur,139922,0.0,137773,2149.0,1463998.0,1225599,114004.0,165096.0,3265933,3008546.0
22,Meghalaya,96783,1.0,95158,1624.0,1332102.0,1024902,30706.0,56987.0,2621058,3276323.0
23,Mizoram,238964,0.0,238238,726.0,785749.0,668814,79573.0,67619.0,1790818,1205974.0
24,Nagaland,35986,0.0,35204,782.0,837775.0,684306,26060.0,43640.0,1737554,2189297.0
25,Odisha,1336552,91.0,1327256,9205.0,31453659.0,29949756,9995330.0,3199384.0,81445474,45429399.0
26,Puducherry,175508,5.0,173528,1975.0,912901.0,801853,303475.0,106956.0,2272617,1397707.0
27,Punjab,784205,49.0,764867,19289.0,22352681.0,19602907,799986.0,1041039.0,46970300,29611935.0
28,Rajasthan,1315455,88.0,1305714,9653.0,51103054.0,46510275,4387205.0,2995864.0,115325059,78230816.0
29,Sikkim,44319,1.0,43819,499.0,539927.0,509134,158276.0,55637.0,1360444,671720.0
30,Tamil Nadu,3594388,60.0,3556279,38049.0,56659544.0,53499923,6033504.0,3021694.0,127442647,76481545.0
31,Telengana,841324,71.0,837142,4111.0,29607672.0,29053708,10525975.0,2702159.0,77201709,38472769.0
32,Tripura,108034,0.0,107094,940.0,2658852.0,2328613,271434.0,204733.0,5916312,4057847.0
33,Uttar Pradesh,2128103,46.0,2104424,23633.0,154058287.0,147716010,35623544.0,9240735.0,390639497,228959599.0
34,Uttarakhand,449379,28.0,441600,7751.0,8180312.0,7940592,1346150.0,867047.0,20051714,11090425.0
35,West Bengal,2118606,58.0,2097016,21532.0,67300236.0,61593452,10257324.0,5491943.0,155962840,97694960.0

In [11]:
df2.fillna(method = 'ffill')

,state,confirmed,active,passive,deaths,dose1,dose2,dose3,precaution_dose,total_doses,population
0,Andaman and Nicobar,10742,1.0,10612,129.0,313284.0,320383,236936.0,53427.0,991263,426251.0
1,Andhra Pradesh,2339067,3.0,2324331,14733.0,40643161.0,43549055,11703273.0,6579565.0,110556756,52883163.0
2,Arunachal Pradesh,66890,3.0,66594,296.0,860442.0,747177,11703273.0,58618.0,1911760,1528296.0
3,Assam,746100,0.0,738065,8035.0,22549957.0,20561790,2082670.0,1259853.0,50284713,34586234.0
4,Bihar,851379,15.0,839062,12302.0,62944633.0,59144387,11983504.0,3868082.0,157197041,119461013.0
5,Chandigarh,99348,6.0,98161,12302.0,1089254.0,917701,48480.0,63046.0,2282281,1182104.0
6,Chhattisgarh,1177749,6.0,1163597,14146.0,1089254.0,18534989,5737679.0,1804891.0,49148991,28566990.0
7,Dadra and Nagar Haveli and Daman and Diu,11591,0.0,11587,4.0,730746.0,594929,136967.0,1804891.0,1578492,657391.0
8,Delhi,2007188,35.0,1980632,26521.0,730746.0,14348835,2312803.0,1053393.0,37366540,18802494.0
9,Delhi,259079,26.0,255040,4013.0,1354828.0,1224173,60838.0,76559.0,2872582,1542750.0
10,Gujarat,1277557,41.0,1266473,11043.0,49314588.0,49428283,13459618.0,5938121.0,127793995,63907200.0
11,Haryana,1056602,43.0,1045845,10714.0,21955717.0,18732346,13459618.0,701811.0,45457359,27388008.0
12,Himachal Pradesh,312644,23.0,308408,4213.0,6041658.0,5780254,1485328.0,823689.0,15278680,7316708.0
13,Jammu and Kashmir,479410,17.0,474608,4785.0,9941757.0,10386967,930096.0,669871.0,24738045,14046258.0
14,Jharkhand,442570,17.0,437236,5331.0,21300448.0,16046070,1306687.0,664308.0,43689818,14046258.0
15,Karnataka,4071893,1275.0,4030311,40307.0,50016690.0,50455767,5727031.0,4726542.0,120928298,66165886.0
16,Kerala,6828245,1389.0,6755304,71552.0,27013745.0,23791879,854595.0,2215656.0,57477992,35330888.0
17,Ladakh,29412,3.0,29178,231.0,219564.0,186942,68766.0,53990.0,564943,307204.0
18,Lakshadweep,11415,0.0,11363,52.0,56908.0,55992,15757.0,6949.0,145008,72210.0
19,Madhya Pradesh,1054918,4.0,1044138,10776.0,54140166.0,54035268,9854998.0,3787239.0,133590886,82342793.0
20,Maharashtra,8136588,164.0,7988008,148416.0,84644083.0,71593498,5022623.0,4450343.0,177678317,120837347.0
21,Manipur,139922,0.0,137773,2149.0,1463998.0,1225599,114004.0,165096.0,3265933,3008546.0
22,Meghalaya,96783,1.0,95158,1624.0,1332102.0,1024902,30706.0,56987.0,2621058,3276323.0
23,Mizoram,238964,0.0,238238,726.0,785749.0,668814,79573.0,67619.0,1790818,1205974.0
24,Nagaland,35986,0.0,35204,782.0,837775.0,684306,26060.0,43640.0,1737554,2189297.0
25,Odisha,1336552,91.0,1327256,9205.0,31453659.0,29949756,9995330.0,3199384.0,81445474,45429399.0
26,Puducherry,175508,5.0,173528,1975.0,912901.0,801853,303475.0,106956.0,2272617,1397707.0
27,Punjab,784205,49.0,764867,19289.0,22352681.0,19602907,799986.0,1041039.0,46970300,29611935.0
28,Rajasthan,1315455,88.0,1305714,9653.0,51103054.0,46510275,4387205.0,2995864.0,115325059,78230816.0
29,Sikkim,44319,1.0,43819,499.0,539927.0,509134,158276.0,55637.0,1360444,671720.0
30,Tamil Nadu,3594388,60.0,3556279,38049.0,56659544.0,53499923,6033504.0,3021694.0,127442647,76481545.0
31,Telengana,841324,71.0,837142,4111.0,29607672.0,29053708,10525975.0,2702159.0,77201709,38472769.0
32,Tripura,108034,0.0,107094,940.0,2658852.0,2328613,271434.0,204733.0,5916312,4057847.0
33,Uttar Pradesh,2128103,46.0,2104424,23633.0,154058287.0,147716010,35623544.0,9240735.0,390639497,228959599.0
34,Uttarakhand,449379,28.0,441600,7751.0,8180312.0,7940592,1346150.0,867047.0,20051714,11090425.0
35,West Bengal,2118606,58.0,2097016,21532.0,67300236.0,61593452,10257324.0,5491943.0,155962840,97694960.0

In [12]:
df2.fillna(method = 'bfill', axis = 1)

,state,confirmed,active,passive,deaths,dose1,dose2,dose3,precaution_dose,total_doses,population
0,Andaman and Nicobar,10742,1.0,10612,129.0,313284.0,320383,236936.0,53427.0,991263,426251.0
1,Andhra Pradesh,2339067,3.0,2324331,14733.0,40643161.0,43549055,11703273.0,6579565.0,110556756,52883163.0
2,Arunachal Pradesh,66890,66594,66594,296.0,860442.0,747177,58618.0,58618.0,1911760,1528296.0
3,Assam,746100,0.0,738065,8035.0,22549957.0,20561790,2082670.0,1259853.0,50284713,34586234.0
4,Bihar,851379,15.0,839062,12302.0,62944633.0,59144387,11983504.0,3868082.0,157197041,119461013.0
5,Chandigarh,99348,6.0,98161,1089254.0,1089254.0,917701,48480.0,63046.0,2282281,1182104.0
6,Chhattisgarh,1177749,6.0,1163597,14146.0,18534989,18534989,5737679.0,1804891.0,49148991,28566990.0
7,Dadra and Nagar Haveli and Daman and Diu,11591,0.0,11587,4.0,730746.0,594929,136967.0,1578492,1578492,657391.0
8,Delhi,2007188,35.0,1980632,26521.0,14348835,14348835,2312803.0,1053393.0,37366540,18802494.0
9,259079.0,259079.0,26.0,255040.0,4013.0,1354828.0,1224173.0,60838.0,76559.0,2872582.0,1542750.0
10,Gujarat,1277557,41.0,1266473,11043.0,49314588.0,49428283,13459618.0,5938121.0,127793995,63907200.0
11,Haryana,1056602,43.0,1045845,10714.0,21955717.0,18732346,701811.0,701811.0,45457359,27388008.0
12,Himachal Pradesh,312644,23.0,308408,4213.0,6041658.0,5780254,1485328.0,823689.0,15278680,7316708.0
13,Jammu and Kashmir,479410,17.0,474608,4785.0,9941757.0,10386967,930096.0,669871.0,24738045,14046258.0
14,Jharkhand,442570,437236,437236,5331.0,21300448.0,16046070,1306687.0,664308.0,43689818,NaN
15,Karnataka,4071893,1275.0,4030311,40307.0,50016690.0,50455767,5727031.0,4726542.0,120928298,66165886.0
16,Kerala,6828245,1389.0,6755304,71552.0,27013745.0,23791879,854595.0,2215656.0,57477992,35330888.0
17,Ladakh,29412,3.0,29178,231.0,219564.0,186942,68766.0,53990.0,564943,307204.0
18,Lakshadweep,11415,0.0,11363,52.0,56908.0,55992,15757.0,6949.0,145008,72210.0
19,Madhya Pradesh,1054918,4.0,1044138,10776.0,54140166.0,54035268,9854998.0,3787239.0,133590886,82342793.0
20,Maharashtra,8136588,164.0,7988008,148416.0,84644083.0,71593498,5022623.0,4450343.0,177678317,120837347.0
21,Manipur,139922,0.0,137773,2149.0,1463998.0,1225599,114004.0,165096.0,3265933,3008546.0
22,Meghalaya,96783,1.0,95158,1624.0,1332102.0,1024902,30706.0,56987.0,2621058,3276323.0
23,Mizoram,238964,0.0,238238,726.0,785749.0,668814,79573.0,67619.0,1790818,1205974.0
24,Nagaland,35986,0.0,35204,782.0,837775.0,684306,26060.0,43640.0,1737554,2189297.0
25,Odisha,1336552,91.0,1327256,9205.0,31453659.0,29949756,9995330.0,3199384.0,81445474,45429399.0
26,Puducherry,175508,5.0,173528,1975.0,912901.0,801853,303475.0,106956.0,2272617,1397707.0
27,Punjab,784205,49.0,764867,19289.0,22352681.0,19602907,799986.0,1041039.0,46970300,29611935.0
28,Rajasthan,1315455,88.0,1305714,9653.0,51103054.0,46510275,4387205.0,2995864.0,115325059,78230816.0
29,Sikkim,44319,1.0,43819,499.0,539927.0,509134,158276.0,55637.0,1360444,671720.0
30,Tamil Nadu,3594388,60.0,3556279,38049.0,56659544.0,53499923,6033504.0,3021694.0,127442647,76481545.0
31,Telengana,841324,71.0,837142,4111.0,29607672.0,29053708,10525975.0,2702159.0,77201709,38472769.0
32,Tripura,108034,0.0,107094,940.0,2658852.0,2328613,271434.0,204733.0,5916312,4057847.0
33,Uttar Pradesh,2128103,46.0,2104424,23633.0,154058287.0,147716010,35623544.0,9240735.0,390639497,228959599.0
34,Uttarakhand,449379,28.0,441600,7751.0,8180312.0,7940592,1346150.0,867047.0,20051714,11090425.0
35,West Bengal,2118606,58.0,2097016,21532.0,67300236.0,61593452,10257324.0,5491943.0,155962840,97694960.0

In [13]:
df2.fillna(method = 'ffill', axis = 1)

,state,confirmed,active,passive,deaths,dose1,dose2,dose3,precaution_dose,total_doses,population
0,Andaman and Nicobar,10742,1.0,10612,129.0,313284.0,320383,236936.0,53427.0,991263,426251.0
1,Andhra Pradesh,2339067,3.0,2324331,14733.0,40643161.0,43549055,11703273.0,6579565.0,110556756,52883163.0
2,Arunachal Pradesh,66890,66890,66594,296.0,860442.0,747177,747177,58618.0,1911760,1528296.0
3,Assam,746100,0.0,738065,8035.0,22549957.0,20561790,2082670.0,1259853.0,50284713,34586234.0
4,Bihar,851379,15.0,839062,12302.0,62944633.0,59144387,11983504.0,3868082.0,157197041,119461013.0
5,Chandigarh,99348,6.0,98161,98161,1089254.0,917701,48480.0,63046.0,2282281,1182104.0
6,Chhattisgarh,1177749,6.0,1163597,14146.0,14146.0,18534989,5737679.0,1804891.0,49148991,28566990.0
7,Dadra and Nagar Haveli and Daman and Diu,11591,0.0,11587,4.0,730746.0,594929,136967.0,136967.0,1578492,657391.0
8,Delhi,2007188,35.0,1980632,26521.0,26521.0,14348835,2312803.0,1053393.0,37366540,18802494.0
9,NaN,259079.0,26.0,255040.0,4013.0,1354828.0,1224173.0,60838.0,76559.0,2872582.0,1542750.0
10,Gujarat,1277557,41.0,1266473,11043.0,49314588.0,49428283,13459618.0,5938121.0,127793995,63907200.0
11,Haryana,1056602,43.0,1045845,10714.0,21955717.0,18732346,18732346,701811.0,45457359,27388008.0
12,Himachal Pradesh,312644,23.0,308408,4213.0,6041658.0,5780254,1485328.0,823689.0,15278680,7316708.0
13,Jammu and Kashmir,479410,17.0,474608,4785.0,9941757.0,10386967,930096.0,669871.0,24738045,14046258.0
14,Jharkhand,442570,442570,437236,5331.0,21300448.0,16046070,1306687.0,664308.0,43689818,43689818
15,Karnataka,4071893,1275.0,4030311,40307.0,50016690.0,50455767,5727031.0,4726542.0,120928298,66165886.0
16,Kerala,6828245,1389.0,6755304,71552.0,27013745.0,23791879,854595.0,2215656.0,57477992,35330888.0
17,Ladakh,29412,3.0,29178,231.0,219564.0,186942,68766.0,53990.0,564943,307204.0
18,Lakshadweep,11415,0.0,11363,52.0,56908.0,55992,15757.0,6949.0,145008,72210.0
19,Madhya Pradesh,1054918,4.0,1044138,10776.0,54140166.0,54035268,9854998.0,3787239.0,133590886,82342793.0
20,Maharashtra,8136588,164.0,7988008,148416.0,84644083.0,71593498,5022623.0,4450343.0,177678317,120837347.0
21,Manipur,139922,0.0,137773,2149.0,1463998.0,1225599,114004.0,165096.0,3265933,3008546.0
22,Meghalaya,96783,1.0,95158,1624.0,1332102.0,1024902,30706.0,56987.0,2621058,3276323.0
23,Mizoram,238964,0.0,238238,726.0,785749.0,668814,79573.0,67619.0,1790818,1205974.0
24,Nagaland,35986,0.0,35204,782.0,837775.0,684306,26060.0,43640.0,1737554,2189297.0
25,Odisha,1336552,91.0,1327256,9205.0,31453659.0,29949756,9995330.0,3199384.0,81445474,45429399.0
26,Puducherry,175508,5.0,173528,1975.0,912901.0,801853,303475.0,106956.0,2272617,1397707.0
27,Punjab,784205,49.0,764867,19289.0,22352681.0,19602907,799986.0,1041039.0,46970300,29611935.0
28,Rajasthan,1315455,88.0,1305714,9653.0,51103054.0,46510275,4387205.0,2995864.0,115325059,78230816.0
29,Sikkim,44319,1.0,43819,499.0,539927.0,509134,158276.0,55637.0,1360444,671720.0
30,Tamil Nadu,3594388,60.0,3556279,38049.0,56659544.0,53499923,6033504.0,3021694.0,127442647,76481545.0
31,Telengana,841324,71.0,837142,4111.0,29607672.0,29053708,10525975.0,2702159.0,77201709,38472769.0
32,Tripura,108034,0.0,107094,940.0,2658852.0,2328613,271434.0,204733.0,5916312,4057847.0
33,Uttar Pradesh,2128103,46.0,2104424,23633.0,154058287.0,147716010,35623544.0,9240735.0,390639497,228959599.0
34,Uttarakhand,449379,28.0,441600,7751.0,8180312.0,7940592,1346150.0,867047.0,20051714,11090425.0
35,West Bengal,2118606,58.0,2097016,21532.0,67300236.0,61593452,10257324.0,5491943.0,155962840,97694960.0

In [15]:
df2.replace(to_replace = 'Bihar', value = 'BIHAR')

,state,confirmed,active,passive,deaths,dose1,dose2,dose3,precaution_dose,total_doses,population
0,Andaman and Nicobar,10742,1.0,10612,129.0,313284.0,320383,236936.0,53427.0,991263,426251.0
1,Andhra Pradesh,2339067,3.0,2324331,14733.0,40643161.0,43549055,11703273.0,6579565.0,110556756,52883163.0
2,Arunachal Pradesh,66890,NaN,66594,296.0,860442.0,747177,NaN,58618.0,1911760,1528296.0
3,Assam,746100,0.0,738065,8035.0,22549957.0,20561790,2082670.0,1259853.0,50284713,34586234.0
4,BIHAR,851379,15.0,839062,12302.0,62944633.0,59144387,11983504.0,3868082.0,157197041,119461013.0
5,Chandigarh,99348,6.0,98161,NaN,1089254.0,917701,48480.0,63046.0,2282281,1182104.0
6,Chhattisgarh,1177749,6.0,1163597,14146.0,NaN,18534989,5737679.0,1804891.0,49148991,28566990.0
7,Dadra and Nagar Haveli and Daman and Diu,11591,0.0,11587,4.0,730746.0,594929,136967.0,NaN,1578492,657391.0
8,Delhi,2007188,35.0,1980632,26521.0,NaN,14348835,2312803.0,1053393.0,37366540,18802494.0
9,NaN,259079,26.0,255040,4013.0,1354828.0,1224173,60838.0,76559.0,2872582,1542750.0
10,Gujarat,1277557,41.0,1266473,11043.0,49314588.0,49428283,13459618.0,5938121.0,127793995,63907200.0
11,Haryana,1056602,43.0,1045845,10714.0,21955717.0,18732346,NaN,701811.0,45457359,27388008.0
12,Himachal Pradesh,312644,23.0,308408,4213.0,6041658.0,5780254,1485328.0,823689.0,15278680,7316708.0
13,Jammu and Kashmir,479410,17.0,474608,4785.0,9941757.0,10386967,930096.0,669871.0,24738045,14046258.0
14,Jharkhand,442570,NaN,437236,5331.0,21300448.0,16046070,1306687.0,664308.0,43689818,NaN
15,Karnataka,4071893,1275.0,4030311,40307.0,50016690.0,50455767,5727031.0,4726542.0,120928298,66165886.0
16,Kerala,6828245,1389.0,6755304,71552.0,27013745.0,23791879,854595.0,2215656.0,57477992,35330888.0
17,Ladakh,29412,3.0,29178,231.0,219564.0,186942,68766.0,53990.0,564943,307204.0
18,Lakshadweep,11415,0.0,11363,52.0,56908.0,55992,15757.0,6949.0,145008,72210.0
19,Madhya Pradesh,1054918,4.0,1044138,10776.0,54140166.0,54035268,9854998.0,3787239.0,133590886,82342793.0
20,Maharashtra,8136588,164.0,7988008,148416.0,84644083.0,71593498,5022623.0,4450343.0,177678317,120837347.0
21,Manipur,139922,0.0,137773,2149.0,1463998.0,1225599,114004.0,165096.0,3265933,3008546.0
22,Meghalaya,96783,1.0,95158,1624.0,1332102.0,1024902,30706.0,56987.0,2621058,3276323.0
23,Mizoram,238964,0.0,238238,726.0,785749.0,668814,79573.0,67619.0,1790818,1205974.0
24,Nagaland,35986,0.0,35204,782.0,837775.0,684306,26060.0,43640.0,1737554,2189297.0
25,Odisha,1336552,91.0,1327256,9205.0,31453659.0,29949756,9995330.0,3199384.0,81445474,45429399.0
26,Puducherry,175508,5.0,173528,1975.0,912901.0,801853,303475.0,106956.0,2272617,1397707.0
27,Punjab,784205,49.0,764867,19289.0,22352681.0,19602907,799986.0,1041039.0,46970300,29611935.0
28,Rajasthan,1315455,88.0,1305714,9653.0,51103054.0,46510275,4387205.0,2995864.0,115325059,78230816.0
29,Sikkim,44319,1.0,43819,499.0,539927.0,509134,158276.0,55637.0,1360444,671720.0
30,Tamil Nadu,3594388,60.0,3556279,38049.0,56659544.0,53499923,6033504.0,3021694.0,127442647,76481545.0
31,Telengana,841324,71.0,837142,4111.0,29607672.0,29053708,10525975.0,2702159.0,77201709,38472769.0
32,Tripura,108034,0.0,107094,940.0,2658852.0,2328613,271434.0,204733.0,5916312,4057847.0
33,Uttar Pradesh,2128103,46.0,2104424,23633.0,154058287.0,147716010,35623544.0,9240735.0,390639497,228959599.0
34,Uttarakhand,449379,28.0,441600,7751.0,8180312.0,7940592,1346150.0,867047.0,20051714,11090425.0
35,West Bengal,2118606,58.0,2097016,21532.0,67300236.0,61593452,10257324.0,5491943.0,155962840,97694960.0

In [6]:
fd = {
    "name":["soham","vishal","vaibhavi","shrusti"],
    "age" : [23,26,28,22],
    "Address": ["maninagar","ghodasar","ab","surat"]
}

sd = pd.DataFrame(fd)
sd

       name  age    Address
0     soham   23  maninagar
1    vishal   26   ghodasar
2  vaibhavi   28         ab
3   shrusti   22      surat

In [7]:
fd1 = {
    "name":["soham","vishal","vaibhavi","shrusti"],
    "age" : [23,26,28,22],
    "Address": ["maninagar","ghodasar","ab","surat"]
}

sd1 = pd.DataFrame(fd1)
sd1

       name  age    Address
0     soham   23  maninagar
1    vishal   26   ghodasar
2  vaibhavi   28         ab
3   shrusti   22      surat

In [8]:
fdd2 = concatnate(fd1, sd1)

NameError: name 'concatnate' is not defined