In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('D:\\vishal data\\csv file\\supermarket_sales.csv')
df

,Invoice_ID,STORE,Customer type,Gender,Product_line,Unit_price,Quantity,Tax _5,Total,Rating,P_date,EEID
0,750-67-8428,B,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,9.1,2019-07-11,101013.0
1,226-31-3081,B,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,9.6,2019-02-13,101018.0
2,631-41-3108,C,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,7.4,2019-06-04,101027.0
3,123-19-1176,D,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,8.4,2019-10-02,101032.0
4,373-73-7910,B,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,5.3,2019-10-29,101015.0
...,...,...,...,...,...,...,...,...,...,...,...,...
295,211-05-0490,E,Member,Female,Electronic accessories,51.92,5,12.9800,272.5800,7.5,2019-08-27,101048.0
296,727-75-6477,D,Normal,Male,Electronic accessories,28.84,4,5.7680,121.1280,6.4,2019-11-21,101031.0
297,744-02-5987,C,Member,Male,Home and lifestyle,78.38,6,23.5140,493.7940,5.8,2019-01-14,101024.0
298,307-83-9164,A,Member,Male,Home and lifestyle,60.01,4,12.0020,252.0420,4.5,2019-12-15,101007.0
299,779-06-0012,D,Member,Female,Home and lifestyle,88.61,1,4.4305,93.0405,7.7,2019-06-30,101037.0

In [3]:
from pivottablejs import pivot_ui
pivot_ui(df)